/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== DEFAULT v4.1.xml ==================
static const unsigned char temp_binary_data_0[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
"\r\n"
"<magic>\r\n"
"  <Styles>\r\n"
"    <Style name=\"default\">\r\n"
"      <Nodes/>\r\n"
"      <Classes>\r\n"
"        <plot-view border=\"2\" background-color=\"black\" border-color=\"silver\" display=\"contents\"/>\r\n"
"        <nomargin margin=\"0\" padding=\"0\" border=\"0\"/>\r\n"
"        <group margin=\"5\" padding=\"5\" border=\"2\" flex-direction=\"column\"/>\r\n"
"        <transparent background-color=\"transparentblack\"/>\r\n"
"      </Classes>\r\n"
"      <Types>\r\n"
"        <Slider border=\"0\" slider-textbox=\"textbox-below\"/>\r\n"
"        <ToggleButton border=\"0\" max-height=\"50\" caption-size=\"0\" text=\"Active\"/>\r\n"
"        <TextButton border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <ComboBox border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <Plot border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"              radius=\"0\"/>\r\n"
"        <XYDragComponent border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"                         radius=\"0\"/>\r\n"
"      </Types>\r\n"
"      <Palettes>\r\n"
"        <default/>\r\n"
"      </Palettes>\r\n"
"    </Style>\r\n"
"  </Styles>\r\n"
"  <View id=\"root\" resizable=\"1\" resize-corner=\"1\" lookAndFeel=\"FoleysFinest\"\r\n"
"        flex-direction=\"column\" caption=\"nvssynthesis::shredverb\" caption-color=\"\"\r\n"
"        border-color=\"FF000000\" background-color=\"FF000000\" tab-color=\"FF000000\"\r\n"
"        width=\"600\" height=\"700\" min-width=\"1\">\r\n"
"    <View flex-grow=\"3\" background-color=\"FF441A1A\" border-color=\"FF441A1A\"\r\n"
"          radius=\"9\" margin=\"2\" padding=\"2\" border=\"2\" min-width=\"500\"\r\n"
"          tab-color=\"FF000000\">\r\n"
"      <View caption=\"QUALIA\" class=\"group\" background-color=\"FF441A1A\" tab-color=\"\"\r\n"
"            border-color=\"FF535252\" flex-shrink=\"1.0\" flex-grow=\"0.7\" caption-size=\"25\"\r\n"
"            caption-color=\"FF644A66\" min-height=\"400\" min-width=\"30\" margin=\"2\">\r\n"
"        <Slider caption=\"Predelay\" parameter=\"predelay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Spatial Size\" parameter=\"size\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Decay\" parameter=\"decay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Highpass Cutoff\" parameter=\"hip\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF441A1A\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Lowpass Cutoff\" parameter=\"lop\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF441A1A\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"SHRED\" class=\"group\" background-color=\"FF441A1A\" border-color=\"FF535252\"\r\n"
"            caption-color=\"FF644A66\" caption-size=\"25\" margin=\"2\" padding=\"0\"\r\n"
"            border=\"2\" min-height=\"400\" flex-align-items=\"\" flex-justify-content=\"\">\r\n"
"        <View flex-direction=\"column\" margin=\"0\" padding=\"3\" border=\"1\" flex-grow=\"4\"\r\n"
"              radius=\"9\" border-color=\"FF535252\">\r\n"
"          <Slider caption=\"Outer Distortion 1\" parameter=\"outer distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" border=\"\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Inner Distortion 1\" parameter=\"inner distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  pos-x=\"-19.3676%\" pos-y=\"46.089%\" pos-width=\"100%\" pos-height=\"24.9097%\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Inner Distortion 2\" parameter=\"inner distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Outer Distortion 2\" parameter=\"outer distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" border-color=\"FF000000\" border=\"\" radius=\"\"/>\r\n"
"        </View>\r\n"
"        <Slider caption=\"Drive\" parameter=\"drive\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                flex-grow=\"0.7\" border-color=\"FF535252\" border=\"2\" padding=\"1\"\r\n"
"                margin=\"1\" radius=\"9\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"ALLPASS\" class=\"group\" flex-grow=\"1.2\" background-color=\"FF441A1A\"\r\n"
"            border-color=\"FF535252\" caption-size=\"25\" caption-color=\"FF644A66\"\r\n"
"            margin=\"2\" min-height=\"400\" flex-wrap=\"nowrap\" flex-justify-content=\"start\">\r\n"
"        <View flex-grow=\"1\" min-width=\"1.0\" flex-order=\"0\" flex-align-self=\"stretch\"\r\n"
"              background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 0\" parameter=\"tvap0 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                  caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                  slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 0\" parameter=\"tvap0 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 1\" parameter=\"tvap1 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                  caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                  slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 1\" parameter=\"tvap1 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 2\" parameter=\"tvap2 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                  caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                  slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 2\" parameter=\"tvap2 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 3\" parameter=\"tvap3 freq\" background-color=\"FF441A1A\"\r\n"
"                  tab-color=\"\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 3\" parameter=\"tvap3 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View caption=\"OUTPUT\" class=\"group\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"            flex-grow=\"0.8\" caption-size=\"25\" caption-color=\"FF644A66\" min-width=\"10\"\r\n"
"            flex-shrink=\"1.0\" min-height=\"400\" margin=\"2\">\r\n"
"        <Slider caption=\"Dry/Wet\" parameter=\"dryWet\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Output Gain\" parameter=\"output gain\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"    <View caption=\"TIMINGS\" class=\"group\" caption-color=\"FF644A66\" background-color=\"FF441A1A\"\r\n"
"          border-color=\"FF441A1A\" caption-size=\"25\" flex-direction=\"row\"\r\n"
"          min-width=\"355\" min-height=\"1.0\" radius=\"9\" border=\"2\" padding=\"1\"\r\n"
"          margin=\"2\" title=\"\">\r\n"
"      <View flex-direction=\"column\" background-color=\"FF441A1A\" padding=\"1\"\r\n"
"            margin=\"1\" border=\"0\" radius=\"1\">\r\n"
"        <Slider caption=\"Outer 1\" parameter=\"delay time 1\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" border-color=\"FF535252\" margin=\"1\"\r\n"
"                padding=\"3\" border=\"2\"/>\r\n"
"        <Slider caption=\"Inner 1\" parameter=\"delay time 0\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" margin=\"1\" padding=\"3\" border=\"2\"\r\n"
"                border-color=\"FF535252\"/>\r\n"
"      </View>\r\n"
"      <View flex-direction=\"column\" background-color=\"FF441A1A\" padding=\"1\"\r\n"
"            margin=\"1\" border-color=\"\" border=\"\">\r\n"
"        <Slider caption=\"Outer 2\" parameter=\"delay time 2\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" border-color=\"FF535252\" border=\"2\"\r\n"
"                padding=\"3\" margin=\"1\"/>\r\n"
"        <Slider caption=\"Inner 2\" parameter=\"delay time 3\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" border-color=\"FF535252\" margin=\"1\"\r\n"
"                padding=\"3\" border=\"2\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"  </View>\r\n"
"</magic>\r\n";

const char* DEFAULT_v4_1_xml = (const char*) temp_binary_data_0;

//================== DEFAULT v2.42.xml ==================
static const unsigned char temp_binary_data_1[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
"\r\n"
"<magic>\r\n"
"  <Styles>\r\n"
"    <Style name=\"default\">\r\n"
"      <Nodes/>\r\n"
"      <Classes>\r\n"
"        <plot-view border=\"2\" background-color=\"black\" border-color=\"silver\" display=\"contents\"/>\r\n"
"        <nomargin margin=\"0\" padding=\"0\" border=\"0\"/>\r\n"
"        <group margin=\"5\" padding=\"5\" border=\"2\" flex-direction=\"column\"/>\r\n"
"        <transparent background-color=\"transparentblack\"/>\r\n"
"      </Classes>\r\n"
"      <Types>\r\n"
"        <Slider border=\"0\" slider-textbox=\"textbox-below\"/>\r\n"
"        <ToggleButton border=\"0\" max-height=\"50\" caption-size=\"0\" text=\"Active\"/>\r\n"
"        <TextButton border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <ComboBox border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <Plot border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"              radius=\"0\"/>\r\n"
"        <XYDragComponent border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"                         radius=\"0\"/>\r\n"
"      </Types>\r\n"
"      <Palettes>\r\n"
"        <default/>\r\n"
"      </Palettes>\r\n"
"    </Style>\r\n"
"  </Styles>\r\n"
"  <View id=\"root\" resizable=\"1\" resize-corner=\"1\" lookAndFeel=\"FoleysFinest\"\r\n"
"        flex-direction=\"column\" caption=\"nvssynthesis::shredverb\" caption-color=\"\"\r\n"
"        min-width=\"1.0\" border-color=\"FF000000\" background-color=\"FF000000\"\r\n"
"        tab-color=\"FF000000\">\r\n"
"    <View flex-grow=\"3\" background-color=\"FF441A1A\" border-color=\"FF441A1A\"\r\n"
"          radius=\"9\" margin=\"2\" padding=\"2\" border=\"2\" min-width=\"500\"\r\n"
"          tab-color=\"FF000000\">\r\n"
"      <View caption=\"QUALIA\" class=\"group\" background-color=\"FF441A1A\" tab-color=\"\"\r\n"
"            border-color=\"FF535252\" flex-shrink=\"1.0\" flex-grow=\"0.7\" caption-size=\"25\"\r\n"
"            caption-color=\"FF644A66\" min-height=\"400\" min-width=\"30\" margin=\"2\">\r\n"
"        <Slider caption=\"Predelay\" parameter=\"predelay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Spatial Size\" parameter=\"size\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Decay\" parameter=\"decay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Lowpass Cutoff\" parameter=\"lop\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF441A1A\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"SHRED\" class=\"group\" background-color=\"FF441A1A\" border-color=\"FF535252\"\r\n"
"            caption-color=\"FF644A66\" caption-size=\"25\" margin=\"2\" padding=\"0\"\r\n"
"            border=\"2\" min-height=\"400\" flex-align-items=\"\" flex-justify-content=\"\">\r\n"
"        <View flex-direction=\"column\" margin=\"0\" padding=\"3\" border=\"1\" flex-grow=\"4\"\r\n"
"              radius=\"9\" border-color=\"FF535252\">\r\n"
"          <Slider caption=\"Outer Distortion 1\" parameter=\"outer distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" border=\"\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Inner Distortion 1\" parameter=\"inner distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  pos-x=\"-19.3676%\" pos-y=\"46.089%\" pos-width=\"100%\" pos-height=\"24.9097%\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Inner Distortion 2\" parameter=\"inner distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Outer Distortion 2\" parameter=\"outer distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" border-color=\"FF000000\" border=\"\" radius=\"\"/>\r\n"
"        </View>\r\n"
"        <Slider caption=\"Drive\" parameter=\"drive\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                flex-grow=\"0.7\" border-color=\"FF535252\" border=\"2\" padding=\"1\"\r\n"
"                margin=\"1\" radius=\"9\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"ALLPASS\" class=\"group\" flex-grow=\"1.2\" background-color=\"FF441A1A\"\r\n"
"            border-color=\"FF535252\" caption-size=\"25\" caption-color=\"FF644A66\"\r\n"
"            margin=\"2\" min-height=\"400\" flex-wrap=\"nowrap\" flex-justify-content=\"start\">\r\n"
"        <View flex-grow=\"1\" min-width=\"1.0\" flex-order=\"0\" flex-align-self=\"stretch\"\r\n"
"              background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 0\" parameter=\"tvap0 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                  caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                  slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 0\" parameter=\"tvap0 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 1\" parameter=\"tvap1 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                  caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                  slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 1\" parameter=\"tvap1 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 2\" parameter=\"tvap2 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                  caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                  slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 2\" parameter=\"tvap2 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 3\" parameter=\"tvap3 freq\" background-color=\"FF441A1A\"\r\n"
"                  tab-color=\"\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 3\" parameter=\"tvap3 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View caption=\"OUTPUT\" class=\"group\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"            flex-grow=\"0.8\" caption-size=\"25\" caption-color=\"FF644A66\" min-width=\"50\"\r\n"
"            flex-shrink=\"1.0\" min-height=\"400\" margin=\"2\">\r\n"
"        <Slider caption=\"Dry/Wet\" parameter=\"dryWet\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Output Gain\" parameter=\"output gain\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"    <View caption=\"TIMINGS\" class=\"group\" caption-color=\"FF644A66\" background-color=\"FF441A1A\"\r\n"
"          border-color=\"FF441A1A\" caption-size=\"25\" flex-direction=\"row\"\r\n"
"          min-width=\"355\" min-height=\"1.0\" radius=\"9\" border=\"2\" padding=\"1\"\r\n"
"          margin=\"2\" title=\"\">\r\n"
"      <View flex-direction=\"column\" background-color=\"FF441A1A\" padding=\"1\"\r\n"
"            margin=\"1\" border=\"0\" radius=\"1\">\r\n"
"        <Slider caption=\"Delay 0\" parameter=\"delay time 0\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" margin=\"1\" padding=\"3\" border=\"2\"\r\n"
"                border-color=\"FF535252\"/>\r\n"
"        <Slider caption=\"Delay 1\" parameter=\"delay time 1\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" border-color=\"FF535252\" margin=\"1\"\r\n"
"                padding=\"3\" border=\"2\"/>\r\n"
"      </View>\r\n"
"      <View flex-direction=\"column\" background-color=\"FF441A1A\" padding=\"1\"\r\n"
"            margin=\"1\" border-color=\"\" border=\"\">\r\n"
"        <Slider caption=\"Delay 2\" parameter=\"delay time 2\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" border-color=\"FF535252\" border=\"2\"\r\n"
"                padding=\"3\" margin=\"1\"/>\r\n"
"        <Slider caption=\"Delay 3\" parameter=\"delay time 3\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" border-color=\"FF535252\" margin=\"1\"\r\n"
"                padding=\"3\" border=\"2\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"  </View>\r\n"
"</magic>\r\n";

const char* DEFAULT_v2_42_xml = (const char*) temp_binary_data_1;

//================== DIRECT EDIT 2.0.xml ==================
static const unsigned char temp_binary_data_2[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
"\r\n"
"<magic>\r\n"
"  <Styles>\r\n"
"    <Style name=\"default\">\r\n"
"      <Nodes/>\r\n"
"      <Classes>\r\n"
"        <plot-view border=\"2\" background-color=\"FF473E51\" border-color=\"silver\"\r\n"
"                   display=\"contents\"/>\r\n"
"        <nomargin margin=\"0\" padding=\"0\" border=\"0\"/>\r\n"
"        <group margin=\"5\" padding=\"5\" border=\"2\" flex-direction=\"column\"/>\r\n"
"        <transparent background-color=\"transparentblack\"/>\r\n"
"      </Classes>\r\n"
"      <Types>\r\n"
"        <Slider border=\"0\" slider-textbox=\"textbox-below\"/>\r\n"
"        <ToggleButton border=\"0\" max-height=\"50\" caption-size=\"0\" text=\"Active\"/>\r\n"
"        <TextButton border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <ComboBox border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <Plot border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"              radius=\"0\"/>\r\n"
"        <XYDragComponent border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"                         radius=\"0\"/>\r\n"
"      </Types>\r\n"
"      <Palettes>\r\n"
"        <default/>\r\n"
"      </Palettes>\r\n"
"    </Style>\r\n"
"  </Styles>\r\n"
"  <View id=\"root\" resizable=\"1\" resize-corner=\"1\" lookAndFeel=\"FoleysFinest\"\r\n"
"        background-color=\"FF473E51\" border-color=\"FF473E51\">\r\n"
"    <View class=\"parameters nomargin\" background-color=\"FF441A1A\" border-color=\"FF1E1D1D\"\r\n"
"          min-width=\"660\" min-height=\"500\">\r\n"
"      <View caption=\"QUALIA\" class=\"group\" background-color=\"FF441A1A\" tab-color=\"\"\r\n"
"            border-color=\"FF535252\" flex-shrink=\"1.0\" flex-grow=\"0.75\" caption-size=\"25\"\r\n"
"            caption-color=\"FF644A66\" min-height=\"680\" min-width=\"30\">\r\n"
"        <Slider caption=\"Drive\" parameter=\"drive\" pos-x=\"4.74308%\" pos-y=\"39.5266%\"\r\n"
"                pos-width=\"100%\" pos-height=\"20%\" caption-placement=\"centred-top\"\r\n"
"                lookAndFeel=\"Skeuomorphic\" background-color=\"FF441A1A\" slider-background=\"FF473E51\"\r\n"
"                slider-thumb=\"FF51548F\" slider-track=\"FF322A39\" caption-color=\"FF906464\"\r\n"
"                slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Predelay\" parameter=\"predelay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Spatial Size\" parameter=\"size\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Decay\" parameter=\"decay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Lowpass Cutoff\" parameter=\"lop\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF441A1A\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"ALLPASS\" class=\"group\" caption-color=\"FF644A66\" background-color=\"FF441A1A\"\r\n"
"            border-color=\"FF535252\" caption-size=\"25\" min-height=\"680\" min-width=\"40\">\r\n"
"        <Slider caption=\"Base Frequency 0\" parameter=\"tvap0 freq\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Bandwidth 0\" parameter=\"tvap0 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Base Frequency 1\" parameter=\"tvap1 freq\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Bandwidth 1\" parameter=\"tvap1 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Base Frequency 2\" parameter=\"tvap2 freq\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Bandwidth 2\" parameter=\"tvap2 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Base Frequency 3\" parameter=\"tvap3 freq\" background-color=\"FF441A1A\"\r\n"
"                tab-color=\"\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Bandwidth 3\" parameter=\"tvap3 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"SHRED\" class=\"group\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"            flex-grow=\"0.85\" caption-size=\"25\" caption-color=\"FF644A66\" min-height=\"680\"\r\n"
"            min-width=\"40\">\r\n"
"        <Slider caption=\"Outer Distortion 1\" parameter=\"outer distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Inner Distortion 1\" parameter=\"inner distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                pos-x=\"-19.3676%\" pos-y=\"46.089%\" pos-width=\"100%\" pos-height=\"24.9097%\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Inner Distortion 2\" parameter=\"inner distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Outer Distortion 2\" parameter=\"outer distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"OUTPUT\" class=\"group\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"            flex-grow=\"0.85\" caption-size=\"25\" caption-color=\"FF644A66\" min-width=\"50\"\r\n"
"            flex-shrink=\"1.0\" min-height=\"680\">\r\n"
"        <Slider caption=\"Dry/Wet\" parameter=\"dryWet\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Output Gain\" parameter=\"output gain\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"  </View>\r\n"
"</magic>\r\n"
"\0\r\n";

const char* DIRECT_EDIT_2_0_xml = (const char*) temp_binary_data_2;

//================== DEFAULT v4.xml ==================
static const unsigned char temp_binary_data_3[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
"\r\n"
"<magic>\r\n"
"  <Styles>\r\n"
"    <Style name=\"default\">\r\n"
"      <Nodes/>\r\n"
"      <Classes>\r\n"
"        <plot-view border=\"2\" background-color=\"black\" border-color=\"silver\" display=\"contents\"/>\r\n"
"        <nomargin margin=\"0\" padding=\"0\" border=\"0\"/>\r\n"
"        <group margin=\"5\" padding=\"5\" border=\"2\" flex-direction=\"column\"/>\r\n"
"        <transparent background-color=\"transparentblack\"/>\r\n"
"      </Classes>\r\n"
"      <Types>\r\n"
"        <Slider border=\"0\" slider-textbox=\"textbox-below\"/>\r\n"
"        <ToggleButton border=\"0\" max-height=\"50\" caption-size=\"0\" text=\"Active\"/>\r\n"
"        <TextButton border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <ComboBox border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <Plot border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"              radius=\"0\"/>\r\n"
"        <XYDragComponent border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"                         radius=\"0\"/>\r\n"
"      </Types>\r\n"
"      <Palettes>\r\n"
"        <default/>\r\n"
"      </Palettes>\r\n"
"    </Style>\r\n"
"  </Styles>\r\n"
"  <View id=\"root\" resizable=\"1\" resize-corner=\"1\" lookAndFeel=\"FoleysFinest\"\r\n"
"        flex-direction=\"column\" caption=\"nvssynthesis::shredverb\" caption-color=\"\"\r\n"
"        min-width=\"1.0\" border-color=\"FF000000\" background-color=\"FF000000\"\r\n"
"        tab-color=\"FF000000\">\r\n"
"    <View flex-grow=\"3\" background-color=\"FF441A1A\" border-color=\"FF441A1A\"\r\n"
"          radius=\"9\" margin=\"2\" padding=\"2\" border=\"2\" min-width=\"500\"\r\n"
"          tab-color=\"FF000000\">\r\n"
"      <View caption=\"QUALIA\" class=\"group\" background-color=\"FF441A1A\" tab-color=\"\"\r\n"
"            border-color=\"FF535252\" flex-shrink=\"1.0\" flex-grow=\"0.7\" caption-size=\"25\"\r\n"
"            caption-color=\"FF644A66\" min-height=\"400\" min-width=\"30\" margin=\"2\">\r\n"
"        <Slider caption=\"Predelay\" parameter=\"predelay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Spatial Size\" parameter=\"size\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Decay\" parameter=\"decay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Lowpass Cutoff\" parameter=\"lop\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF441A1A\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"SHRED\" class=\"group\" background-color=\"FF441A1A\" border-color=\"FF535252\"\r\n"
"            caption-color=\"FF644A66\" caption-size=\"25\" margin=\"2\" padding=\"0\"\r\n"
"            border=\"2\" min-height=\"400\" flex-align-items=\"\" flex-justify-content=\"\">\r\n"
"        <View flex-direction=\"column\" margin=\"0\" padding=\"3\" border=\"1\" flex-grow=\"4\"\r\n"
"              radius=\"9\" border-color=\"FF535252\">\r\n"
"          <Slider caption=\"Outer Distortion 1\" parameter=\"outer distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" border=\"\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Inner Distortion 1\" parameter=\"inner distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  pos-x=\"-19.3676%\" pos-y=\"46.089%\" pos-width=\"100%\" pos-height=\"24.9097%\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Inner Distortion 2\" parameter=\"inner distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Outer Distortion 2\" parameter=\"outer distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                  margin=\"1\" padding=\"2\" border-color=\"FF000000\" border=\"\" radius=\"\"/>\r\n"
"        </View>\r\n"
"        <Slider caption=\"Drive\" parameter=\"drive\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-track=\"FF322A39\" slider-background=\"FF473E51\"\r\n"
"                slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"\r\n"
"                flex-grow=\"0.7\" border-color=\"FF535252\" border=\"2\" padding=\"1\"\r\n"
"                margin=\"1\" radius=\"9\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"ALLPASS\" class=\"group\" flex-grow=\"1.2\" background-color=\"FF441A1A\"\r\n"
"            border-color=\"FF535252\" caption-size=\"25\" caption-color=\"FF644A66\"\r\n"
"            margin=\"2\" min-height=\"400\" flex-wrap=\"nowrap\" flex-justify-content=\"start\">\r\n"
"        <View flex-grow=\"1\" min-width=\"1.0\" flex-order=\"0\" flex-align-self=\"stretch\"\r\n"
"              background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 0\" parameter=\"tvap0 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                  caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                  slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 0\" parameter=\"tvap0 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 1\" parameter=\"tvap1 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                  caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                  slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 1\" parameter=\"tvap1 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 2\" parameter=\"tvap2 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                  caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                  slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 2\" parameter=\"tvap2 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 3\" parameter=\"tvap3 freq\" background-color=\"FF441A1A\"\r\n"
"                  tab-color=\"\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"          <Slider caption=\"Width 3\" parameter=\"tvap3 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View caption=\"OUTPUT\" class=\"group\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"            flex-grow=\"0.8\" caption-size=\"25\" caption-color=\"FF644A66\" min-width=\"50\"\r\n"
"            flex-shrink=\"1.0\" min-height=\"400\" margin=\"2\">\r\n"
"        <Slider caption=\"Dry/Wet\" parameter=\"dryWet\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"        <Slider caption=\"Output Gain\" parameter=\"output gain\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                slider-text-background=\"FF280A32\" slider-text-highlight=\"FFDF00FF\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"    <View caption=\"TIMINGS\" class=\"group\" caption-color=\"FF644A66\" background-color=\"FF441A1A\"\r\n"
"          border-color=\"FF441A1A\" caption-size=\"25\" flex-direction=\"row\"\r\n"
"          min-width=\"355\" min-height=\"1.0\" radius=\"9\" border=\"2\" padding=\"1\"\r\n"
"          margin=\"2\" title=\"\">\r\n"
"      <View flex-direction=\"column\" background-color=\"FF441A1A\" padding=\"1\"\r\n"
"            margin=\"1\" border=\"0\" radius=\"1\">\r\n"
"        <Slider caption=\"Outer 1\" parameter=\"delay time 1\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" border-color=\"FF535252\" margin=\"1\"\r\n"
"                padding=\"3\" border=\"2\"/>\r\n"
"        <Slider caption=\"Inner 1\" parameter=\"delay time 0\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" margin=\"1\" padding=\"3\" border=\"2\"\r\n"
"                border-color=\"FF535252\"/>\r\n"
"      </View>\r\n"
"      <View flex-direction=\"column\" background-color=\"FF441A1A\" padding=\"1\"\r\n"
"            margin=\"1\" border-color=\"\" border=\"\">\r\n"
"        <Slider caption=\"Outer 2\" parameter=\"delay time 2\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" border-color=\"FF535252\" border=\"2\"\r\n"
"                padding=\"3\" margin=\"1\"/>\r\n"
"        <Slider caption=\"Inner 2\" parameter=\"delay time 3\" background-color=\"FF441A1A\"\r\n"
"                slider-background=\"FF473E51\" slider-track=\"FF322A39\" slider-thumb=\"FF51548F\"\r\n"
"                caption-color=\"FF906464\" slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\"\r\n"
"                slider-text-highlight=\"FFDF00FF\" border-color=\"FF535252\" margin=\"1\"\r\n"
"                padding=\"3\" border=\"2\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"  </View>\r\n"
"</magic>\r\n";

const char* DEFAULT_v4_xml = (const char*) temp_binary_data_3;

//================== DEFAULT v5.xml ==================
static const unsigned char temp_binary_data_4[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
"\r\n"
"<magic>\r\n"
"  <Styles>\r\n"
"    <Style name=\"default\">\r\n"
"      <Nodes/>\r\n"
"      <Classes>\r\n"
"        <plot-view border=\"2\" background-color=\"black\" border-color=\"silver\" display=\"contents\"/>\r\n"
"        <nomargin margin=\"0\" padding=\"0\" border=\"0\"/>\r\n"
"        <group margin=\"5\" padding=\"5\" border=\"2\" flex-direction=\"column\"/>\r\n"
"        <transparent background-color=\"transparentblack\"/>\r\n"
"      </Classes>\r\n"
"      <Types>\r\n"
"        <Slider border=\"0\" slider-textbox=\"textbox-below\"/>\r\n"
"        <ToggleButton border=\"0\" max-height=\"50\" caption-size=\"0\" text=\"Active\"/>\r\n"
"        <TextButton border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <ComboBox border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <Plot border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"              radius=\"0\"/>\r\n"
"        <XYDragComponent border=\"0\" margin=\"0\" padding=\"0\" background-color=\"FF473E51\"\r\n"
"                         radius=\"0\"/>\r\n"
"      </Types>\r\n"
"      <Palettes>\r\n"
"        <default/>\r\n"
"      </Palettes>\r\n"
"    </Style>\r\n"
"  </Styles>\r\n"
"  <View id=\"root\" resizable=\"1\" resize-corner=\"1\" lookAndFeel=\"FoleysFinest\"\r\n"
"        flex-direction=\"column\" caption=\"nvssynthesis::shredverb\" caption-color=\"\"\r\n"
"        border-color=\"FF000000\" background-color=\"FF000000\" tab-color=\"FF000000\"\r\n"
"        width=\"600\" height=\"700\" min-width=\"100\" min-height=\"100\">\r\n"
"    <View flex-grow=\"3\" background-color=\"FF441A1A\" border-color=\"FF441A1A\"\r\n"
"          radius=\"9\" margin=\"2\" padding=\"2\" border=\"2\" min-width=\"500\"\r\n"
"          tab-color=\"FF000000\">\r\n"
"      <View caption=\"QUALIA\" class=\"group\" background-color=\"FF441A1A\" tab-color=\"\"\r\n"
"            border-color=\"FF535252\" flex-shrink=\"1.0\" flex-grow=\"0.7\" caption-size=\"25\"\r\n"
"            caption-color=\"FF644A66\" min-height=\"400\" min-width=\"30\" margin=\"2\">\r\n"
"        <Slider caption=\"Predelay\" parameter=\"predelay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"        <Slider caption=\"Spatial Size\" parameter=\"size\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"        <Slider caption=\"Decay\" parameter=\"decay\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"        <Slider caption=\"Highpass Cutoff\" parameter=\"hip\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF441A1A\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"        <Slider caption=\"Lowpass Cutoff\" parameter=\"lop\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF441A1A\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"SHRED\" class=\"group\" background-color=\"FF441A1A\" border-color=\"FF535252\"\r\n"
"            caption-color=\"FF644A66\" caption-size=\"25\" margin=\"2\" padding=\"0\"\r\n"
"            border=\"2\" min-height=\"400\" flex-align-items=\"\" flex-justify-content=\"\">\r\n"
"        <View flex-direction=\"column\" margin=\"0\" padding=\"3\" border=\"1\" flex-grow=\"2.9\"\r\n"
"              radius=\"9\" border-color=\"FF535252\">\r\n"
"          <Slider caption=\"Outer Distortion 1\" parameter=\"outer distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-track=\"FF322A39\" caption-size=\"20\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" caption-color=\"FF906464\"\r\n"
"                  slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"\r\n"
"                  margin=\"1\" padding=\"8\" border=\"\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Inner Distortion 1\" parameter=\"inner distortion 1\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  pos-x=\"-19.3676%\" pos-y=\"46.089%\" pos-width=\"100%\" pos-height=\"24.9097%\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                  caption-size=\"20\" slider-thumb=\"FF51548F\" caption-color=\"FF906464\"\r\n"
"                  slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"\r\n"
"                  margin=\"1\" padding=\"8\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Inner Distortion 2\" parameter=\"inner distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-track=\"FF322A39\"\r\n"
"                  caption-size=\"20\" slider-thumb=\"FF51548F\" caption-color=\"FF906464\"\r\n"
"                  slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"\r\n"
"                  margin=\"1\" padding=\"8\" radius=\"0\"/>\r\n"
"          <Slider caption=\"Outer Distortion 2\" parameter=\"outer distortion 2\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                  background-color=\"FF441A1A\" slider-track=\"FF322A39\" caption-size=\"20\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" caption-color=\"FF906464\"\r\n"
"                  slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"\r\n"
"                  margin=\"1\" padding=\"8\" border-color=\"FF000000\" border=\"0\" radius=\"\"/>\r\n"
"        </View>\r\n"
"        <Slider caption=\"Drive\" parameter=\"drive\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-track=\"FF322A39\" caption-size=\"20\"\r\n"
"                slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" caption-color=\"FF906464\"\r\n"
"                slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"\r\n"
"                flex-grow=\"0.7\" border-color=\"FF535252\" border=\"0\" padding=\"8\"\r\n"
"                margin=\"1\" radius=\"9\"/>\r\n"
"      </View>\r\n"
"      <View caption=\"ALLPASS\" class=\"group\" flex-grow=\"1.2\" background-color=\"FF441A1A\"\r\n"
"            border-color=\"FF535252\" caption-size=\"25\" caption-color=\"FF644A66\"\r\n"
"            margin=\"2\" min-height=\"400\" flex-wrap=\"nowrap\" flex-justify-content=\"start\">\r\n"
"        <View flex-grow=\"1\" min-width=\"1.0\" flex-order=\"0\" flex-align-self=\"stretch\"\r\n"
"              background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 0\" parameter=\"tvap0 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-track=\"FF322A39\" caption-size=\"20\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"          <Slider caption=\"Width 0\" parameter=\"tvap0 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                  slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 1\" parameter=\"tvap1 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                  caption-size=\"20\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"          <Slider caption=\"Width 1\" parameter=\"tvap1 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                  slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 2\" parameter=\"tvap2 freq\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-thumb=\"FF51548F\" slider-track=\"FF322A39\"\r\n"
"                  caption-size=\"20\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"          <Slider caption=\"Width 2\" parameter=\"tvap2 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                  slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"        </View>\r\n"
"        <View background-color=\"FF441A1A\" border=\"1\" border-color=\"FF535252\"\r\n"
"              radius=\"5\" margin=\"1\" padding=\"1\">\r\n"
"          <Slider caption=\"Base 3\" parameter=\"tvap3 freq\" background-color=\"FF441A1A\"\r\n"
"                  tab-color=\"\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                  slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"          <Slider caption=\"Width 3\" parameter=\"tvap3 bandwidth\" lookAndFeel=\"FoleysFinest\"\r\n"
"                  background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                  slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                  slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View caption=\"OUTPUT\" class=\"group\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"            flex-grow=\"0.8\" caption-size=\"25\" caption-color=\"FF644A66\" min-width=\"10\"\r\n"
"            flex-shrink=\"1.0\" min-height=\"400\" margin=\"2\">\r\n"
"        <Slider caption=\"Dry/Wet\" parameter=\"dryWet\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"        <Slider caption=\"Output Gain\" parameter=\"output gain\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                background-color=\"FF441A1A\" slider-background=\"FF473E51\" slider-thumb=\"FF51548F\"\r\n"
"                slider-track=\"FF322A39\" caption-size=\"20\" caption-color=\"FF906464\"\r\n"
"                slider-text=\"FF8B4747\" slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"    <View caption=\"TIMINGS\" class=\"group\" caption-color=\"FF644A66\" background-color=\"FF441A1A\"\r\n"
"          border-color=\"FF441A1A\" caption-size=\"25\" flex-direction=\"row\"\r\n"
"          min-width=\"355\" min-height=\"60\" radius=\"9\" border=\"2\" padding=\"1\"\r\n"
"          margin=\"2\" title=\"\">\r\n"
"      <View flex-direction=\"column\" background-color=\"FF441A1A\" padding=\"1\"\r\n"
"            margin=\"1\" border=\"0\" radius=\"1\">\r\n"
"        <View margin=\"2\" border=\"0\" lookAndFeel=\"FoleysFinest\" padding=\"8\"\r\n"
"              radius=\"2\" border-color=\"FF535252\" background-color=\"FF441A1A\">\r\n"
"          <Slider caption=\"Outer Time 1\" parameter=\"delay time 1\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-track=\"FF322A39\" caption-size=\"20\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"\r\n"
"                  border-color=\"FF535252\" margin=\"0\" padding=\"0\" border=\"0\" flex-grow=\"4\"\r\n"
"                  radius=\"0\" pos-x=\"-1.54799%\" pos-y=\"-10.7527%\" pos-width=\"79.8762%\"\r\n"
"                  pos-height=\"100%\"/>\r\n"
"          <Slider slider-type=\"rotary-horizontal-vertical\" parameter=\"g0\" caption=\"Outer g1\"\r\n"
"                  caption-color=\"FF906464\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"                  margin=\"0\" padding=\"0\" border=\"0\" radius=\"0\" slider-text=\"FF8B4747\"\r\n"
"                  slider-background=\"\" slider-text-background=\"FF280A32\"/>\r\n"
"        </View>\r\n"
"        <View margin=\"2\" border=\"0\" padding=\"8\" radius=\"2\" border-color=\"FF535252\"\r\n"
"              background-color=\"FF441A1A\">\r\n"
"          <Slider caption=\"Inner Time 1\" parameter=\"delay time 0\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-track=\"FF322A39\" caption-size=\"20\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"\r\n"
"                  margin=\"0\" padding=\"0\" border=\"0\" border-color=\"FF535252\" flex-grow=\"4\"\r\n"
"                  radius=\"0\"/>\r\n"
"          <Slider slider-type=\"rotary-horizontal-vertical\" parameter=\"g1\" caption=\"Inner g1\"\r\n"
"                  caption-color=\"FF906464\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"                  margin=\"0\" padding=\"0\" border=\"0\" radius=\"0\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View flex-direction=\"column\" background-color=\"FF441A1A\" padding=\"1\"\r\n"
"            margin=\"1\" border=\"0\" radius=\"1\">\r\n"
"        <View margin=\"2\" border=\"0\" padding=\"8\" radius=\"2\" border-color=\"FF535252\"\r\n"
"              background-color=\"FF441A1A\">\r\n"
"          <Slider slider-type=\"rotary-horizontal-vertical\" parameter=\"g2\" caption=\"Outer g2\"\r\n"
"                  caption-color=\"FF906464\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"                  margin=\"0\" padding=\"0\" border=\"0\" radius=\"0\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\"/>\r\n"
"          <Slider caption=\"Outer Time 2\" parameter=\"delay time 2\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-track=\"FF322A39\" caption-size=\"20\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"\r\n"
"                  border-color=\"FF535252\" border=\"0\" padding=\"0\" margin=\"0\" flex-grow=\"4\"\r\n"
"                  radius=\"0\"/>\r\n"
"        </View>\r\n"
"        <View margin=\"2\" padding=\"8\" border=\"0\" radius=\"2\" border-color=\"FF535252\"\r\n"
"              background-color=\"FF441A1A\">\r\n"
"          <Slider slider-type=\"rotary-horizontal-vertical\" parameter=\"g3\" caption=\"Inner g2\"\r\n"
"                  caption-color=\"FF906464\" border-color=\"FF535252\" background-color=\"FF441A1A\"\r\n"
"                  margin=\"0\" padding=\"0\" border=\"0\" radius=\"0\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\"/>\r\n"
"          <Slider caption=\"Inner Time 2\" parameter=\"delay time 3\" background-color=\"FF441A1A\"\r\n"
"                  slider-background=\"FF473E51\" slider-track=\"FF322A39\" caption-size=\"20\"\r\n"
"                  slider-thumb=\"FF51548F\" caption-color=\"FF906464\" slider-text=\"FF8B4747\"\r\n"
"                  slider-text-background=\"FF280A32\" slider-text-highlight=\"FF7B3197\"\r\n"
"                  border-color=\"FF535252\" margin=\"0\" padding=\"0\" border=\"0\" flex-grow=\"4\"\r\n"
"                  radius=\"0\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"  </View>\r\n"
"</magic>\r\n";

const char* DEFAULT_v5_xml = (const char*) temp_binary_data_4;


const char* getNamedResource (const char* resourceNameUTF8, int& numBytes);
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)
{
    unsigned int hash = 0;

    if (resourceNameUTF8 != nullptr)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0xa9b63e66:  numBytes = 13375; return DEFAULT_v4_1_xml;
        case 0xbfe8695b:  numBytes = 12993; return DEFAULT_v2_42_xml;
        case 0xeae37c9c:  numBytes = 9394; return DIRECT_EDIT_2_0_xml;
        case 0xd54ac2b4:  numBytes = 12993; return DEFAULT_v4_xml;
        case 0xd558da35:  numBytes = 16110; return DEFAULT_v5_xml;
        default: break;
    }

    numBytes = 0;
    return nullptr;
}

const char* namedResourceList[] =
{
    "DEFAULT_v4_1_xml",
    "DEFAULT_v2_42_xml",
    "DIRECT_EDIT_2_0_xml",
    "DEFAULT_v4_xml",
    "DEFAULT_v5_xml"
};

const char* originalFilenames[] =
{
    "DEFAULT v4.1.xml",
    "DEFAULT v2.42.xml",
    "DIRECT EDIT 2.0.xml",
    "DEFAULT v4.xml",
    "DEFAULT v5.xml"
};

const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8);
const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8)
{
    for (unsigned int i = 0; i < (sizeof (namedResourceList) / sizeof (namedResourceList[0])); ++i)
        if (strcmp (namedResourceList[i], resourceNameUTF8) == 0)
            return originalFilenames[i];

    return nullptr;
}

}
